-- CoF/Tea Café POS — Supabase schema + seed data
-- Run this entire file in Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.app_users (id bigint generated by default as identity primary key, auth_user_id uuid unique references auth.users(id) on delete cascade, email text unique not null, username text unique not null, name text not null default '', role text not null default 'staff' check (role in ('owner','staff')), active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.products (id bigint generated by default as identity primary key, product_id text unique not null, category text not null, name text not null, p12 numeric(10,2) not null default 0, p16 numeric(10,2) not null default 0, p22 numeric(10,2) not null default 0, active boolean not null default true, unique(category,name));
create table if not exists public.inventory (id bigint generated by default as identity primary key, sku text unique not null, name text not null, category text not null, unit text not null default 'pcs', inside numeric(12,2) not null default 0, outside numeric(12,2) not null default 0, stock_in numeric(12,2) not null default 0, adjustments numeric(12,2) not null default 0, reorder numeric(12,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.sales (id bigint generated by default as identity primary key, transaction_id text unique not null, sale_date date not null, sale_time time not null, subtotal numeric(12,2) not null default 0, total numeric(12,2) not null default 0, payment_method text not null, cash_received numeric(12,2) not null default 0, change_amount numeric(12,2) not null default 0, user_id bigint references public.app_users(id), status text not null default 'completed', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.sale_items (id bigint generated by default as identity primary key, sale_id bigint not null references public.sales(id) on delete cascade, product_name text not null, category text not null default '', size text not null default '', temperature text not null default 'Cold', quantity numeric(12,2) not null default 1, unit_price numeric(12,2) not null default 0, addon text not null default 'No Add-on', addon_price numeric(12,2) not null default 0, tutti_frutti boolean not null default false, free_upsize boolean not null default false, original_size text, free_drink boolean not null default false, customized boolean not null default false, line_total numeric(12,2) not null default 0);
create table if not exists public.expenses (id bigint generated by default as identity primary key, expense_date date not null, category text not null, description text not null, amount numeric(12,2) not null, payment_method text not null default 'Cash', notes text not null default '', created_at timestamptz not null default now());
create table if not exists public.historical (id bigint generated by default as identity primary key, record_date date not null, sales numeric(12,2) not null default 0, expenses numeric(12,2) not null default 0, cash_sales numeric(12,2) not null default 0, gcash_sales numeric(12,2) not null default 0, cash_expenses numeric(12,2) not null default 0, gcash_expenses numeric(12,2) not null default 0, cups numeric(12,2) not null default 0, notes text not null default '', created_at timestamptz not null default now());
create table if not exists public.report_adjustments (id bigint generated by default as identity primary key, type text not null check(type in ('daily','monthly','yearly')), key text not null, sales_delta numeric(12,2) not null default 0, cash_delta numeric(12,2) not null default 0, gcash_delta numeric(12,2) not null default 0, expenses_delta numeric(12,2) not null default 0, cups_delta numeric(12,2) not null default 0, updated_at timestamptz not null default now(), unique(type,key));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.app_users(auth_user_id,email,username,name,role,active) values(new.id,new.email,coalesce(nullif(new.raw_user_meta_data->>'username',''),split_part(new.email,'@',1)),coalesce(nullif(new.raw_user_meta_data->>'name',''),split_part(new.email,'@',1)),case when lower(coalesce(new.raw_user_meta_data->>'role','staff'))='owner' then 'owner' else 'staff' end,true) on conflict (auth_user_id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.lookup_login_email(p_username text) returns table(email text, active boolean) language sql security definer set search_path=public as $$ select u.email,u.active from public.app_users u where lower(u.username)=lower(trim(p_username)) limit 1; $$;
grant execute on function public.lookup_login_email(text) to anon,authenticated;

create or replace function public.current_app_role() returns text language sql stable security definer set search_path=public as $$ select role from public.app_users where auth_user_id=auth.uid() and active=true limit 1; $$;

alter table public.app_users enable row level security;
alter table public.products enable row level security;
alter table public.inventory enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.expenses enable row level security;
alter table public.historical enable row level security;
alter table public.report_adjustments enable row level security;
drop policy if exists app_users_self_or_owner on public.app_users;
create policy app_users_self_or_owner on public.app_users for select to authenticated using (auth_user_id=auth.uid() or public.current_app_role()='owner');
drop policy if exists app_users_update_self on public.app_users;
create policy app_users_update_self on public.app_users for update to authenticated using (auth_user_id=auth.uid()) with check (auth_user_id=auth.uid());
drop policy if exists products_auth_all on public.products;
create policy products_auth_all on public.products for all to authenticated using (true) with check (true);
drop policy if exists inventory_auth_all on public.inventory;
create policy inventory_auth_all on public.inventory for all to authenticated using (true) with check (true);
drop policy if exists sales_auth_all on public.sales;
create policy sales_auth_all on public.sales for all to authenticated using (true) with check (true);
drop policy if exists sale_items_auth_all on public.sale_items;
create policy sale_items_auth_all on public.sale_items for all to authenticated using (true) with check (true);
drop policy if exists expenses_auth_all on public.expenses;
create policy expenses_auth_all on public.expenses for all to authenticated using (true) with check (true);
drop policy if exists historical_auth_all on public.historical;
create policy historical_auth_all on public.historical for all to authenticated using (true) with check (true);
drop policy if exists report_adjustments_auth_all on public.report_adjustments;
create policy report_adjustments_auth_all on public.report_adjustments for all to authenticated using (true) with check (true);

insert into public.products(product_id,category,name,p12,p16,p22) values
('P001','Cafe Latte','Original Latte',39,49,59),
('P002','Cafe Latte','Spanish Latte',39,49,59),
('P003','Cafe Latte','Strawberry Latte',39,49,59),
('P004','Cafe Latte','Hazelnut Brew',39,49,59),
('P005','Cafe Latte','Caramel Macchiato',39,49,59),
('P006','Cafe Latte','Chocolate Latte',39,49,59),
('P007','Cafe Latte','Salted Caramel',39,49,59),
('P008','Cafe Latte','Vanilla Blanca',39,49,59),
('P009','Cafe Latte','White Cappuccino',39,49,59),
('P010','Cafe Latte','Matcha Latte',49,59,69),
('P011','Cafe Latte','Red Velvet',49,59,69),
('P012','Amerikano','Original',39,49,59),
('P013','Amerikano','Caramel Macchiato',39,49,59),
('P014','Amerikano','Hazelnut Brew',39,49,59),
('P015','Amerikano','Salted Caramel',39,49,59),
('P016','Amerikano','Black Cappuccino',39,49,59),
('P017','Amerikano Twist','Red Velvet',49,59,69),
('P018','Amerikano Twist','Orange Americano',49,59,69),
('P019','Amerikano Twist','Lychee Americano',49,59,69),
('P020','Amerikano Twist','Blueberry Americano',49,59,69),
('P021','Milktea','Original',39,49,59),
('P022','Milktea','Okinawa',39,49,59),
('P023','Milktea','Wintermelon',39,49,59),
('P024','Milktea','Cookies & Cream',39,49,59),
('P025','Milktea','Hokkaido',39,49,59),
('P026','Milktea','Purple Taro',39,49,59),
('P027','Milktea','Brown Sugar',39,49,59),
('P028','Milktea','Chocolate',39,49,59),
('P029','Milktea','Green Matcha',49,59,69),
('P030','Milktea','Red Velvet',49,59,69),
('P031','Frappe','Java Chip',59,69,79),
('P032','Frappe','Vanilla Espresso',59,69,79),
('P033','Frappe','Wintermelon Espresso',59,69,79),
('P034','Frappe','Okinawa Espresso',59,69,79),
('P035','Frappe','Hokkaido Espresso',59,69,79),
('P036','Frappe','Cheesecake',59,69,79),
('P037','Frappe','Cookies & Cream',59,69,79),
('P038','Frappe','Dark Choco',59,69,79),
('P039','Frappe','Strawberry',59,69,79),
('P040','Frappe','Matcha',59,69,79),
('P041','Frappe','Red Velvet',59,69,79),
('P042','Fruit Series','Green Apple',39,49,59),
('P043','Fruit Series','Blueberry',39,49,59),
('P044','Fruit Series','Kiwi',39,49,59),
('P045','Fruit Series','Lychee',39,49,59),
('P046','Fruit Series','Strawberry',39,49,59),
('P047','Fruit Series','Passionfruit',39,49,59),
('P048','Fruit Series','Honey Peach',39,49,59),
('P049','Soda Series','Green Apple',49,59,69),
('P050','Soda Series','Blueberry',49,59,69),
('P051','Soda Series','Kiwi',49,59,69),
('P052','Soda Series','Lychee',49,59,69),
('P053','Soda Series','Strawberry',49,59,69),
('P054','Soda Series','Passionfruit',49,59,69),
('P055','Soda Series','Honey Peach',49,59,69)
on conflict (product_id) do update set category=excluded.category,name=excluded.name,p12=excluded.p12,p16=excluded.p16,p22=excluded.p22,active=true;

insert into public.inventory(sku,name,category,unit,inside,outside,stock_in) values
('INV-001','Cheesecake','Powder','pcs',0,0,0),
('INV-002','Cookies & Cream','Powder','pcs',0,0,0),
('INV-003','Cream Cheese','Powder','pcs',0,0,0),
('INV-004','Creamer','Powder','pcs',0,0,0),
('INV-005','Dark Chocolate','Powder','pcs',0,0,0),
('INV-006','Java Chip','Powder','pcs',0,0,0),
('INV-007','Matcha','Powder','pcs',0,0,0),
('INV-008','Red Velvet','Powder','pcs',0,0,0),
('INV-009','Whipping Cream','Powder','pcs',0,0,0),
('INV-010','Blueberry','Syrup','pcs',0,0,0),
('INV-011','Brown Sugar','Syrup','pcs',0,0,0),
('INV-012','Caramel','Syrup','pcs',0,0,0),
('INV-013','Caramel Drizzle','Syrup','pcs',0,0,0),
('INV-014','Chocolate','Syrup','pcs',0,0,0),
('INV-015','Green Apple','Syrup','pcs',0,0,0),
('INV-016','Hazelnut','Syrup','pcs',0,0,0),
('INV-017','Hokkaido','Syrup','pcs',0,0,0),
('INV-018','Kiwi','Syrup','pcs',0,0,0),
('INV-019','Lychee','Syrup','pcs',0,0,0),
('INV-020','Okinawa','Syrup','pcs',0,0,0),
('INV-021','Passion Fruit','Syrup','pcs',0,0,0),
('INV-022','Salted Caramel','Syrup','pcs',0,0,0),
('INV-023','Strawberry','Syrup','pcs',0,0,0),
('INV-024','Sweetener','Syrup','pcs',0,0,0),
('INV-025','Taro','Syrup','pcs',0,0,0),
('INV-026','Vanilla','Syrup','pcs',0,0,0),
('INV-027','White Chocolate','Syrup','pcs',0,0,0),
('INV-028','Wintermelon','Syrup','pcs',0,0,0),
('INV-029','Coffee','Tea & Coffee','pcs',0,0,0),
('INV-030','Tea','Tea & Coffee','pcs',0,0,0),
('INV-031','Nata','Other','pcs',0,0,0),
('INV-032','Pearl','Other','pcs',0,0,0),
('INV-033','Powdered Sugar','Other','pcs',0,0,0),
('INV-034','Sprite','Other','pcs',0,0,0),
('INV-035','Sugar','Other','pcs',0,0,0),
('INV-036','Condensed','Other','pcs',0,0,0),
('INV-037','12 oz','Cups','pcs',0,0,0),
('INV-038','16 oz','Cups','pcs',0,0,0),
('INV-039','22 oz','Cups','pcs',0,0,0),
('INV-040','Hot Cups','Cups','pcs',0,0,0),
('INV-041','Dome Lids','Packaging','pcs',0,0,0),
('INV-042','Regular Lids','Packaging','pcs',0,0,0),
('INV-043','Large Straws','Packaging','pcs',0,0,0),
('INV-044','Small (Paper & Plastic) Straws','Packaging','pcs',0,0,0),
('INV-045','Double Take-out Bags','Packaging','pcs',0,0,0),
('INV-046','Single Take-out Bags','Packaging','pcs',0,0,0)
on conflict (sku) do update set name=excluded.name,category=excluded.category,unit=excluded.unit;

grant usage on schema public to authenticated;
grant select,insert,update,delete on public.app_users,public.products,public.inventory,public.sales,public.sale_items,public.expenses,public.historical,public.report_adjustments to authenticated;

create or replace function public.save_sale(p_sale_id bigint, p_items jsonb, p_payment text, p_cash numeric, p_user_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_sale_id bigint; v_tx text; v_total numeric(12,2); v_cash numeric(12,2); v_change numeric(12,2); v_date date:=current_date; v_time time:=localtime; r record; cup_qty numeric; inv record;
begin
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'Order is empty.'; end if;
 select coalesce(sum((x->>'lineTotal')::numeric*greatest(1,coalesce((x->>'qty')::numeric,1))),0) into v_total from jsonb_array_elements(p_items)x;
 v_cash:=case when p_payment='Cash' then greatest(0,coalesce(p_cash,0)) else 0 end;
 if p_payment='Cash' and v_cash<v_total then raise exception 'Cash received is less than total.'; end if;
 v_change:=case when p_payment='Cash' then v_cash-v_total else 0 end;
 if p_sale_id is not null then
   select * into r from public.sales where id=p_sale_id and status='completed' for update; if not found then raise exception 'Sale not found.'; end if;
   for r in select case when size='12oz' then '12 oz' when size='16oz' then '16 oz' when size='22oz' then '22 oz' else 'Hot Cups' end cname,sum(quantity) qty from public.sale_items where sale_id=p_sale_id group by 1 loop update public.inventory set outside=outside+r.qty,updated_at=now() where name=r.cname; end loop;
   delete from public.sale_items where sale_id=p_sale_id;
   update public.sales set sale_date=v_date,sale_time=v_time,subtotal=v_total,total=v_total,payment_method=p_payment,cash_received=v_cash,change_amount=v_change,user_id=coalesce(p_user_id,user_id),updated_at=now() where id=p_sale_id;
   v_sale_id:=p_sale_id; select transaction_id into v_tx from public.sales where id=v_sale_id;
 else
   v_tx:='TRX-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
   insert into public.sales(transaction_id,sale_date,sale_time,subtotal,total,payment_method,cash_received,change_amount,user_id,status) values(v_tx,v_date,v_time,v_total,v_total,p_payment,v_cash,v_change,p_user_id,'completed') returning id into v_sale_id;
 end if;
 for r in select case when x->>'size'='12oz' then '12 oz' when x->>'size'='16oz' then '16 oz' when x->>'size'='22oz' then '22 oz' else 'Hot Cups' end cname,sum(greatest(1,coalesce((x->>'qty')::numeric,1))) qty from jsonb_array_elements(p_items)x group by 1 loop
   select * into inv from public.inventory where name=r.cname for update;
   if found and coalesce(inv.inside,0)+coalesce(inv.outside,0)+coalesce(inv.stock_in,0)+coalesce(inv.adjustments,0)<r.qty then raise exception 'Not enough % cups. Remaining: %',r.cname,(coalesce(inv.inside,0)+coalesce(inv.outside,0)+coalesce(inv.stock_in,0)+coalesce(inv.adjustments,0)); end if;
   if found then cup_qty:=least(coalesce(inv.outside,0),r.qty); update public.inventory set outside=outside-cup_qty,inside=greatest(0,inside-(r.qty-cup_qty)),updated_at=now() where id=inv.id; end if;
 end loop;
 insert into public.sale_items(sale_id,product_name,category,size,temperature,quantity,unit_price,addon,addon_price,tutti_frutti,free_upsize,original_size,free_drink,customized,line_total)
 select v_sale_id,x->>'product',coalesce(x->>'category',''),coalesce(x->>'size',''),coalesce(x->>'temperature','Cold'),greatest(1,coalesce((x->>'qty')::numeric,1)),coalesce((x->>'unit')::numeric,0),coalesce(x->>'addon','No Add-on'),coalesce((x->>'addonPrice')::numeric,0),coalesce((x->>'tutti')::boolean,false),coalesce((x->>'freeUpsize')::boolean,false),nullif(x->>'originalSize',''),coalesce((x->>'freeDrink')::boolean,false),coalesce((x->>'customized')::boolean,false),coalesce((x->>'lineTotal')::numeric,0) from jsonb_array_elements(p_items)x;
 return jsonb_build_object('ok',true,'transactionId',v_tx);
end; $$;
create or replace function public.delete_sale(p_sale_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$ declare r record; begin select * into r from public.sales where id=p_sale_id and status='completed' for update; if not found then raise exception 'Sale not found.'; end if; for r in select case when size='12oz' then '12 oz' when size='16oz' then '16 oz' when size='22oz' then '22 oz' else 'Hot Cups' end cname,sum(quantity) qty from public.sale_items where sale_id=p_sale_id group by 1 loop update public.inventory set outside=outside+r.qty,updated_at=now() where name=r.cname; end loop; update public.sales set status='deleted',updated_at=now() where id=p_sale_id; return jsonb_build_object('ok',true); end; $$;
grant execute on function public.save_sale(bigint,jsonb,text,numeric,bigint) to authenticated;
grant execute on function public.delete_sale(bigint) to authenticated;
alter publication supabase_realtime add table public.products;
alter publication supabase_realtime add table public.inventory;
alter publication supabase_realtime add table public.sales;
alter publication supabase_realtime add table public.sale_items;
alter publication supabase_realtime add table public.expenses;
alter publication supabase_realtime add table public.historical;
alter publication supabase_realtime add table public.report_adjustments;
alter publication supabase_realtime add table public.app_users;
